version: '3.8'

services:
  db:
    image: postgres:17.3  # Используем последнюю версию PostgreSQL
    container_name: church-db
    env_file:
      - ".env"  # Используем переменные окружения из файла .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Переменные из .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - my_network
    volumes:
      - ./${DUMP_NAME}:/docker-entrypoint-initdb.d/${DUMP_NAME}
      - postgres_data:/var/lib/postgresql/data  # Сохраняем данные PostgreSQL
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'" ]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .  # Собираем образ из Dockerfile
    working_dir: /church
    command: bash -c "python manage.py migrate && python manage.py shell -c \"import os; from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser(os.environ.get('ADMIN_USER'), os.environ.get('ADMIN_EMAIL'), os.environ.get('ADMIN_PASSWORD'))\" && python manage.py runserver 0.0.0.0:8000"  # Команда для запуска Django  # Монтируем текущую директорию в /church внутри контейнера
    env_file:
      - ".env"  # Используем переменные окружения из файла .env
    networks:
      - my_network
    depends_on:
      db:
        condition: service_healthy
networks:
  my_network:
    driver: bridge
volumes:
  postgres_data:  # Том для хранения данных PostgreSQL