version: '3.8'

services:
  db:
    image: postgres:17.3  # Используем последнюю версию PostgreSQL
    container_name: church-db
    env_file:
      - ".env"  # Используем переменные окружения из файла .env
    environment:
      POSTGRES_USER: ${USER}  # Переменные из .env
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
    ports:
      - "5432:5432"  # Пробрасываем порт 5432 для доступа к PostgreSQL
    volumes:
      - ./${DUMP_NAME}:/dump/${DUMP_NAME}
      - postgres_data:/var/lib/postgresql/data  # Сохраняем данные PostgreSQL

  web:
    build: .  # Собираем образ из Dockerfile
    working_dir: /church
    command: python manage.py runserver 0.0.0.0:8000  # Команда для запуска Django  # Монтируем текущую директорию в /church внутри контейнера    volumes: - .:/church/church
    ports:
      - "8000:8000"  # Пробрасываем порт 8000 для доступа к Django
    env_file:
      - ".env"  # Используем переменные окружения из файла .env
    environment:
      - DB_HOST=db  # Переменные для подключения к PostgreSQL
      - DB_NAME=${NAME}
      - DB_USER=${USER}
      - DB_PASSWORD=${PASSWORD}
    depends_on:
      - db  # Зависимость от сервиса db

volumes:
  postgres_data:  # Том для хранения данных PostgreSQL